<?php
return array(
    'content' => '
        <h4>AviviD Innovative Media Blog Ad Placement Revenue Sharing Agreement</h4>
        <h5>
            <ul>
                <li>This Blog Ad Placement Revenue Sharing Agreement (the “Agreement”) is written to govern the ad revenue sharing program (the “Program”) between AviviD Innovative Media (the “Company”) and AviviD service subscriber (the “Applicant”), both whom agree to be bound by this Agreement.</li>
                <li>WHEREAS, Company has developed Likr, POPAI, Unitoday, and 券券-券券聯盟 (the “Service”) and holds ownership of all intellectual property rights in the Service;</li>
                <li>WHEREAS, Company is the developer and operator of the Program and holds ownership of all intellectual property rights in the Program;</li>
                <li>WHEREAS, the Applicant desires to use at one of the Service and/or participate the Program to generate revenue;</li>
                <li>WHEREAS, the Company and the Applicant desire to enter into an arrangement whereby the Company and the Applicant will share the revenue realized from the usage of the Service and/or Ad placement of the Program due to the efforts of the Applicant according to the terms and conditions herein.</li>
                <li>WHEREAS, THEREFORE, in consideration of the mutual covenants and promises made by the Parties hereto, the Company and the Applicant (individually, each a Party and collectively, the “Parties”) covenant and agree as follows:</li>
            </ul>
        </h5>
    ',
    'text_list_style_type' => 'decimal',
    'text' => '
        <ol>
            <li>Applicant must be at least 20 years old at the time of entering this agreement. If the Applicant is under the age of 20 years old at the time of entering this Agreement, a legal representative must resume the responsibilities of (a) understanding the terms and conditions set by this Agreement prior to entering the Agreement and (b) entering the contract on Applicant’s behave. Once the agreement is entered by Parties, Applicant consents that he/she is at least 20 years old or a legal representative has resumed the responsibilities of understanding the terms and conditions set by this Agreement and entering the agreement on his/her behave.</li>
            <li>If the Applicant is already a subscriber of the Service, Applicant can apply for the Program through Company’s blogger portal. Once the application is approved, a Program account can be created. If the Applicant is not a subscriber of the Service, Applicant would need to subscribe to the Service prior to applying for the Program.</li>
            <li>Applicant entered the Program is entitled to share an agreed percentage of revenue generated from the Ads placed on Applicant’s blog(s).</li>
            <li>The Parties agree that Parties shall be considered independent contractors and not agents or employees of the other Party. Neither Party shall have authority to make any statements, representations or commitments of any kind, nor to take any action which shall be binding on the other Party, except as may be expressly provided for herein or authorized in writing. The Applicant consents that Applicant’s blog(s) does not have any inappropriate content including but not limited to pornography, violence, illegal software download, crime advocation, piracy, and defamation. The Company reserves the rights to (a) suspend any Program account associated to any blog that has inappropriate content, and (b) withhold or cancel any revenue sharing payment. Applicant is responsible for any legal liability resulted from the content violation. When a Program account is suspended, the revenue sharing balance would also stop to accumulate.</li>
            <li>When a program account is suspended, the Applicant has the right to dispute the suspension and provide supporting evidences within 30 days. The supporting evidences can include but not limited to court document, settlement agreement, and Company recognized document.</li>
            <li>The Agreement prohibits the Applicant from engaging the following acts: using auto ad clicking software, Ad hiding, or any other methods that drives impression and click count outside of normal user driven viewing and clicking activities. If the Applicant was found to engage any prohibited act, the Company reserves the rights to (a) suspend any Program account associated to any blog t, (b) withhold or cancel revenue sharing payment, and (c) take legal action against Applicant over the violation. The Application has the rights stated in (5) to dispute any complaint resulted from prohibited acts listed in this paragraph.</li>	
            <li>Applicant shall not directly or indirectly disclose or educate anyone on any method that encourages or enables anyone to engage any prohibited activity including but not limited to the ones listed in (6) with the intention to drive Ad view or click on Applicant’s blog(s).</li>
            <li>The Parties agree on the following revenue sharing methods.
                <ul>
                    <li>Ad Revenue: Ad revenue would be calculated base on CPC (Cost Per Click). The Company would deduct all associated fees from generated revenue, and then share an agreed percentage of generated revenue with Applicant.</li>
                    <li>券券-券券聯盟: The revenue for 券券-券券聯盟 would be calculated based on CPS (Cost per Sales). The Company would deduct all associated fees from generated revenue, and then share an agreed percentage of generated revenue with Applicant.</li>
                </ul>
            </li>
            <li>When the Applicant’s revenue sharing balance is accumulated to $1,000 NTD, the balance would be processed between the 10th and 15th day of the following month and the actual earned amount would be disbursed on the 25th day of the following month from the process date. If the disbursement date is on a holiday, the disbursement would be postponed to the next business day.</li>
            <li>The Company will charge a service fee of $30 NTD for each fund disbursement. The service fee would be deducted directly from the disbursement amount. For example, if an Applicant earns $1,000 NTD in a given month, the actual amount the Applicant would receive is $970 NTD ($1,000 NTD - $30 NTD = $970 NTD). If the earned amount is calculated to decimals, any amount less than $1 NTD would be rolled over to the next statement.</li>
            <li>The income from the Program for the Applicant is not subjected to tax withhold. Every January, the Company would report the earning from previous year to tax agencies in Taiwan. The Company will send all tax statements to applicable Applicants. The income from the Program is not subjected to 2nd Generation NHI premium deduction. If the Applicant is not a citizen of Republic of China or is a non-resident (living in Taiwan less than 183 days in a tax-year) of Republic of China, the Applicant would be subjected to 20% income tax withhold. If the Applicant is a citizen of Republic of China or lived in Taiwan at least 183 days within the tax-year with resident permit, then the Applicant is only required to file proper report but not tax withhold.</li>
            <li>The Program account is subjected to bi-yearly review. If a Program becomes inactive (without share revenue accumulation or disbursement request) for over 2 years, the Company reserves the right to terminate the Program account and disburse the remaining balance in the account. If the Applicant has at least $1,000 NTD accumulated in his/her Program account at the time of review, the Company will disburse the amount as stated in (9). If the Applicant has less than $1,000 NTD accumulated in his/her Program account at the time of review, the Applicant agrees that the Company can use the fund for any charity purpose.</li>
            <li>The Company reserves the right to modify the agreed revenue sharing structure and/or payment term of the Program at any time, and the Company will notify the Applicant when any change is made. If the Applicant does not agree with the modification made by the Company, the Applicant can withdraw his/her participation from the Program. If the Applicant has at least $1,000 NTD accumulated in his/her Program account at the time of withdrawing from the Program, the Company will disburse the amount as stated in (9). If the Applicant has less than $1,000 NTD accumulated in his/her Program account at the time of withdrawing from the Program, the Applicant agrees that the Company can use the fund for any charity purpose.</li>
            <li>Applicant acknowledges that the Company does not guarantee any earning amount from the Program, and the Applicant is responsible to make his/her own efforts to generate revenue from the Program.</li>
            <li>Applicant acknowledge that the Company is not liable to any lost or damage done to the Applicant or any of Applicant’s property. The Applicant hereby waives all rights to take any action against the Company.</li>
            <li>Company acknowledges that Company cannot disclose Applicant’s information to public without order from any governmental agency or consent from Applicant.</li>
            <li>The Company reserves the right to modify the terms and conditions of this agreement at any time without notifying the Applicant. If the Applicant does not agree with the modification made by the Company, the Applicant can withdraw his/her participation from the Program. The Company reserves the rights to terminate Applicant’s some or all participation(s) of the Program. Unless the Applicant violates any of the terms and conditions stated in Agreement, the Company shall disburse the earned revenue to the Applicant within 30 business days.</li>
            <li>Applicant is liable for any lost and damage done to the company as result of Applicant’s action.</li>
            <li>The terms and conditions set by the Agreement is independent from each other. Any controversy or claim arising out of or relating to this Agreement or the breach thereof, shall be settled by litigation administered by the Taipei District Court in accordance with its law, and judgment on the award rendered by the judge(s) may be entered in any court having jurisdiction thereof.</li>
            <li>Applicant authorizes Company to collect, use, and process all information (including but not limited to name, email address, phone number, and etc.) submitted. Company will not disclose the information to 3rd party without order from any governmental agency or consent from Applicant. The information submitted by the Applicant will solely be used for all lawful business purposes by the Company. The Applicant has the rights to modify, add, or delete any information submitted to the Company. (However, the Company and the Program might not be able to fully service the Applicant without needed and accurate information required.) If the Applicant would like to exercise any of the rights set by this Agreement, please contact the Company directly.</li>
        </ul>
    ',
    'check' => 'I agree AviviD Innovative Media Blog Ad Placement Revenue Sharing Agreement',
    'confirm' => 'Confirm',
)
?>